### ISSUE TITLE
Helper utils (/solved, /postembed etc)

### ISSUE THREAD

**Issue by junepark678** [palera1n/bot-rewrite#10]
will add channel checks for /postembed
/solved seems to be finished

**Comment by junepark678** [comment]
#6 partially solves /solved. however, i would like a better perms system instead of in-function checks. I also do not know if the code even works

**Comment by JanCraft** [comment]
Still have to add the description modal to /postembed since I didn't know it existed.

**Comment by junepark678** [comment]
#14 fixes this
