### ISSUE TITLE
Timeouts add 1 wp unless keyword is used

### ISSUE THREAD

**Issue by JanCraft** [palera1n/bot-rewrite#30]
Yet to decide:
 - keyword vs unix flag (`... sleep` or `... --sleep`)
 - hardcoded list or dynamic list (use database)

**Comment by junepark678** [comment]
i would hide the `--sleep` in logs if we do get to that point and add them in a separate section like `flags`
i would also like to add things like `-w 2` (for 2 warn points) or `--warnpoints=2` (longer variation)
this should also hide
now that i think about it, hardcoded seems fine ngl
