### ISSUE TITLE
Social media embed fixer

### ISSUE THREAD

**Issue by 0xallie** [palera1n/bot-rewrite#38]
- vxtwitter.com
- ddinstagram.com
- quickvids.win (TikTok)

**Comment by Beast9265** [comment]
I agree gn because its like 2:20am

**Comment by plooshi** [comment]
vxtwitter should be pretty simple, just remove the embed from the original message and then replace twitter.com with vxtwitter.com using .replace

**Comment by itsnebulalol** [comment]
I also have the code for how to use the QuickVids API.

**Comment by itsnebulalol** [comment]
All finished in [a9593d8](https://github.com/palera1n/bot-rewrite/commit/a9593d86f9f81f5f22ae68c90751988890479e57) (#40).
